### PR TITLE
use yaml.safe_load

### PR DESCRIPTION
**Pull request by rb-determined-ai**
Avoid arbitrary code-injection.

### CODE REVIEW

**Comment by amitbeka** [comment]
Thanks a lot!

Do you find this useful? how do you use conda-merge?

**Comment by rb-determined-ai** [comment]
Yes!  I was struggling with a clean way to 1) build a docker container using a base conda environment, then 2) add a layer to the container which merges in some configurable secondary environment, in a clean way that can't overwrite the specifications that were written into the first.  I would basically have written this tool if it hadn't existed.  It's a really neat tool!

The one thing I have doubts about is the tie-breaking behavior of the channel merging.  For instance, at one point I had a base environment whose channels were like (this is not an exact example, I'm having to do this from memory):
```
channels:
 - my-local-conda-forge-mirror
 - defaults 
```
Then I merged an environment like:
```
channels:
 - conda-forge
 - defaults
```
The result was something to the effect of:
```
channels:
 - conda-forge
 - my-local-conda-forge-mirror
 - defaults
```
My understanding is that the result is a valid topological sort (`defaults` comes after `my-local-conda-forge-mirror`) but it seems unexpected that a package from my secondary environment unnecessarily precedes a package from my base environment.  So to guarantee that one of my channels supersedes a user-given channel, I would have to explicitly mention both channels in my base environment:
```
channels:
 - my-local-conda-forge-mirror
 - conda-forge # explicitly mention this channel that might appear in the secondary
               # environment, even thought I don't actually want anything from this
               # channel
 - defaults 
```
And that's not so bad in the example I show here, since every local-mirror channel needs to supersede exactly one known channel name, but I could imagine in more complex environments that this could lead to unexpected behavior.  And in general, it seems like the channel merge should prefer channels from the base environment to be sooner, if it doesn't violate the topological sort.

**Comment by amitbeka** [comment]
First, thanks for the feedback :)
Second, I'll look at the code to see how easy it is to have this behavior (base env channels before children) configurable and not set in stone.

**Comment by rb-determined-ai** [comment]
I mean... to me the behavior of topographical sort first, followed by base channels second... that makes a lot of sense to me.  Even if it wasn't configurable.  But I am a fairly new conda user, so I don't pretend to understand all the possible use cases.

**Comment by amitbeka** [comment]
I just released a new version for the package.
Topological sort is still the main concern, as it provides the most correct behavior.
However, within same-level channels (have the same dependencies, it at all), I prefer the first ones added (from the base env) over the later ones.

**Comment by rb-determined-ai** [comment]
Awesome!  Thank you!

**Pull request merged**
